### ISSUE TITLE
Flameshow seems better than tfg

### ISSUE THREAD

**Issue by amosbird** [azat/chdig#5]
https://github.com/laixintao/flameshow

**Comment by azat** [comment]
Thanks for the tip!

Though there are some issues with it:
- [x] distribution (`pyinstaller` cannot handle it, but `PyOxidizer` could) - done
- [x] size (instead of 8MiB for tfg it requires 25MiB at least stripped and compressed, but suppose this OK)
- [ ] ensure that the input format is correct
- [ ] there are some terminal manipulation overlaps between `chdig` and `flameshow`

Once I will fix this, tfg could be replaced.

But long term goal is to rewrite it to Rust.

**Comment by amosbird** [comment]
Perfect!

Btw, it seems PyOxidizer allows embedding python code into rust. And it explicitly serves as a python-to-rust helper, which meets the long term goal :

> While solving packaging and distribution problems is the primary goal of PyOxidizer, a side-effect of solving that problem with Rust is that PyOxidizer can serve as a bridge between these two languages. PyOxidizer can be used to easily add a Python interpreter to any Rust project. But the opposite is also true: PyOxidizer can also be used to add Rust to Python. Using PyOxidizer, you could bootstrap a new Rust project which contains an embedded version of Python and your application. Initially, your project is a few lines of Rust that instantiates a Python interpreter and runs Python code. Over time, functionality could be (re)written in Rust and your previously Python-only project could leverage Rust and its diverse ecosystem. Since PyOxidizer abstracts the Python interpreter away, this could all be invisible to end-users: you could rewrite an application from Python to Rust and people may not even know because they never see a libpython, .py files, etc.

**Comment by azat** [comment]
>it seems PyOxidizer allows embedding python code into rust

Indeed!
I already added this into my todo list

**Comment by azat** [comment]
P.S. maybe I should convert my todo list into issues on github...

**Comment by azat** [comment]
It is not that transparent, but looks like it works more or less OK - https://github.com/azat/chdig/commit/ccfa72d0bc30e87b1a55b9dab6bebcf73eb2244f
